# Generated by Django 2.0.4 on 2018-07-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='phone_number',
            field=models.TextField(null=True),
        ),
    ]
