# Generated by Django 2.0.7 on 2018-07-15 11:12

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_person_display_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='display_picture',
            field=models.ImageField(null=True, upload_to=main.models.upload_to_func),
        ),
    ]
