# Generated by Django 2.0.7 on 2018-07-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20180715_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('roll', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
