# Generated by Django 2.0.4 on 2018-07-17 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_book_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
    ]
