# Generated by Django 2.0.7 on 2018-07-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_person_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
