# Generated by Django 2.0.7 on 2018-07-15 11:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20180715_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.CharField(max_length=256, null=True, validators=[django.core.validators.EmailValidator]),
        ),
    ]
